# Generated by Django 6.0.7 on 2026-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0002_alter_user_managers_remove_user_school_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
