# Generated by Django 6.0.7 on 2026-09-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0004_transactiontype_formrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available_slots', models.PositiveIntegerField(help_text='Remaining capacity for this window.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slot_date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='formrequest',
            name='requires_archive_retrieval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='processing_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='required_documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('purpose', models.CharField(choices=[('Employment', 'Employment'), ('Further studies', 'Further studies'), ('Scholarship', 'Scholarship'), ('Other', 'Other')], max_length=30)),
                ('purpose_other', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='TrailSync.formrequest')),
            ],
        ),
        migrations.AddField(
            model_name='formrequest',
            name='release_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_requests', to='TrailSync.releaseslot'),
        ),
    ]
