# Generated by Django 6.0.7 on 2026-09-09 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0005_releaseslot_formrequest_requires_archive_retrieval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='number_of_copies',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='formsubmission',
            name='purpose_other',
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='board_exam_photo',
            field=models.FileField(blank=True, null=True, upload_to='board_exam_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RequestProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Spouse', 'Spouse'), ('Friend', 'Friend'), ('Other', 'Other')], max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy', to='TrailSync.formrequest')),
            ],
        ),
    ]
