# Generated by Django 6.0.7 on 2026-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0006_remove_formsubmission_number_of_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formrequest',
            name='request_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Ready', 'Ready for Pickup'), ('Released', 'Released'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
    ]
