# Generated by Django 6.0.7 on 2026-09-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0007_alter_formrequest_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='common_purposes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='special_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
