# Generated by Django 6.0.7 on 2026-09-09 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0008_transactiontype_common_purposes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Status & Tracking', 'Status & Tracking'), ('Requirements & Process', 'Requirements & Process'), ('Claim Stub & Pickup', 'Claim Stub & Pickup'), ('Account/Technical', 'Account/Technical'), ('General Info', 'General Info')], max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ entry',
                'verbose_name_plural': 'FAQ entries',
            },
        ),
        migrations.AddField(
            model_name='formrequest',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='arrival_notice_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='claim_stub_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='clearance_check_result',
            field=models.CharField(blank=True, choices=[('Active - No Check Needed', 'Active - No Check Needed'), ('Cleared', 'Cleared'), ('Not Cleared', 'Not Cleared')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='clearance_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='clearance_checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_checks', to='TrailSync.staffprofile'),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='digital_stub_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='duplicate_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='is_rush',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='or_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='processing_time_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReleaseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimant_name', models.CharField(blank=True, max_length=150, null=True)),
                ('claimant_signature', models.FileField(blank=True, null=True, upload_to='claim_signatures/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_schedule', to='TrailSync.formrequest')),
            ],
        ),
    ]
