# Generated by Django 6.0.7 on 2026-09-09 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0009_faqentry_formrequest_amount_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Rejected', 'Rejected')], max_length=20)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='TrailSync.formrequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_made', to='TrailSync.staffprofile')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
