# Generated by Django 6.0.7 on 2026-09-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0010_requirementverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseslot',
            name='available_slots',
            field=models.PositiveIntegerField(help_text='Total capacity for this window (see class docstring).'),
        ),
    ]
