# Generated by Django 6.0.7 on 2026-09-11 04:30

import django.db.models.deletion
from django.db import migrations, models

# Statuses at or past Registrar approval under the current 5-value
# RequestStatus enum. Duplicated as literals rather than imported from the
# model because a data migration must run against the schema as it was at
# THIS point in history, not against whatever models.py says today.
APPROVED_STATUSES = ("Verified", "Ready", "Released")


def backfill_approval_and_amount(apps, schema_editor):
    """Give already-approved requests the approval attribution and amount
    due that the new columns expect.

    Without this, any request approved before this migration would print a
    Cashier form with a blank amount and no signatory — the two columns
    would be NULL forever, since they're only ever written at approval time
    and those approvals already happened. The attribution is recovered from
    RequirementVerification, which has been recording verified_by/verified_at
    all along; amount_due is recomputed from the fee schedule.
    """
    FormRequest = apps.get_model("TrailSync", "FormRequest")

    for req in FormRequest.objects.filter(
        request_status__in=APPROVED_STATUSES
    ).select_related("transaction_type"):
        updated_fields = []

        if req.registrar_approved_at is None:
            latest = (
                req.verifications.filter(verification_status="Verified")
                .order_by("-verified_at")
                .first()
            )
            if latest is not None:
                req.registrar_approved_by_id = latest.verified_by_id
                req.registrar_approved_at = latest.verified_at
            else:
                # Approved before RequirementVerification existed. The exact
                # approval moment is unrecoverable, so updated_at is the
                # closest honest approximation and the signatory stays NULL
                # (the form falls back to printing the office, not a name,
                # rather than inventing one).
                req.registrar_approved_at = req.updated_at
            updated_fields += ["registrar_approved_by", "registrar_approved_at"]

        if req.amount_due is None and req.transaction_type.fee_amount is not None:
            submission = getattr(req, "submission", None)
            raw_copies = ((submission.form_data if submission else None) or {}).get(
                "number_of_copies"
            )
            try:
                copies = int(raw_copies)
            except (TypeError, ValueError):
                copies = 1
            req.amount_due = req.transaction_type.fee_amount * max(1, copies)
            updated_fields.append("amount_due")

        if updated_fields:
            req.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0011_alter_releaseslot_available_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrequest',
            name='registrar_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='registrar_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrar_approvals', to='TrailSync.staffprofile'),
        ),
        # Reverse is a no-op: the columns this populates are dropped by the
        # AddField reversals above, so there is nothing to undo.
        migrations.RunPython(backfill_approval_and_amount, migrations.RunPython.noop),
    ]
