# Generated by Django 6.0.7 on 2026-09-11 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def verified_to_approved(apps, schema_editor):
    """Rewrite the retired "Verified" request_status to "Approved".

    The lifecycle gained an explicit Processing stage between approval and
    pickup, and the old value was renamed to match what the step actually
    means. AlterField only changes the choices Django validates against - the
    rows still hold the old string - so without this every already-approved
    request would sit on a value no longer in the enum: absent from the
    Processing Queue's filters and failing the guards on the new transition
    endpoints.

    ReleaseSchedule rows that already have a claimed_at are stamped Claimed
    for the same reason: the column defaults to "Scheduled", which would
    misreport an already-collected document as still waiting.
    """
    FormRequest = apps.get_model("TrailSync", "FormRequest")
    moved = FormRequest.objects.filter(request_status="Verified").update(
        request_status="Approved"
    )

    ReleaseSchedule = apps.get_model("TrailSync", "ReleaseSchedule")
    claimed = ReleaseSchedule.objects.filter(claimed_at__isnull=False).update(
        release_status="Claimed"
    )
    print(f"    migrated {moved} request(s) Verified -> Approved, {claimed} schedule(s) -> Claimed")


def approved_to_verified(apps, schema_editor):
    """Reverse: put the old value back so this migration can be unapplied.

    Lossy in one direction only - a request that reached Processing or later
    has no pre-lifecycle equivalent, so those are left alone rather than
    collapsed into a stage they had already moved past.
    """
    FormRequest = apps.get_model("TrailSync", "FormRequest")
    FormRequest.objects.filter(request_status="Approved").update(request_status="Verified")


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0012_formrequest_registrar_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseschedule',
            name='release_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Claimed', 'Claimed')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='formrequest',
            name='request_status',
            field=models.CharField(choices=[('Submitted', 'Pending Verification'), ('Approved', 'Approved - Ready to Print'), ('Processing', 'Processing'), ('Ready', 'Ready for Pickup'), ('Released', 'Released'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Approved', 'Approved - Ready to Print'), ('Processing', 'Processing'), ('Ready', 'Ready for Pickup'), ('Released', 'Released'), ('Rejected', 'Rejected')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='TrailSync.formrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
            migrations.RunPython(verified_to_approved, approved_to_verified),
    ]
