# Generated by Django 6.0.7 on 2026-09-11 09:25

import django.db.models.deletion
from django.db import migrations, models


def backfill_schedule_from_slot(apps, schema_editor):
    """Copy the booked slot onto any schedule row that predates these columns.

    A ReleaseSchedule written before this migration has no release_date, so
    scheduled_release() would fall through to the FormRequest's slot - fine
    while that slot is still set, but the new Mark Ready flow can clear it
    when staff chooses a freeform time. Stamping the values now means those
    rows carry their own date instead of depending on a link that may later
    be removed.
    """
    ReleaseSchedule = apps.get_model("TrailSync", "ReleaseSchedule")
    stamped = 0
    for schedule in ReleaseSchedule.objects.filter(release_date__isnull=True).select_related(
        "form_request__release_slot"
    ):
        slot = schedule.form_request.release_slot
        if slot is None:
            continue
        schedule.release_date = slot.slot_date
        schedule.release_time_start = slot.start_time
        schedule.release_slot_id = slot.id
        schedule.save(update_fields=["release_date", "release_time_start", "release_slot"])
        stamped += 1
    print(f"    stamped {stamped} existing schedule(s) from their booked slot")


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0013_releaseschedule_release_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseschedule',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releaseschedule',
            name='release_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_schedules', to='TrailSync.releaseslot'),
        ),
        migrations.AddField(
            model_name='releaseschedule',
            name='release_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
            migrations.RunPython(backfill_schedule_from_slot, migrations.RunPython.noop),
    ]
