# Generated by Django 6.0.7 on 2026-09-11 10:12

from decimal import Decimal

from django.db import migrations, models

# form_data.purpose values, old -> new. The earlier set was invented before
# anyone had read FM-USTP-RGTR-09; these are Part 3 of the real form.
PURPOSE_RENAMES = {
    "Employment": "For Employment",
    "Further studies": "For Advanced Studies",
    "Scholarship": "For Scholarship",
    "Board Exam": "For Board Exam",
    "Other": "Others",
}

# The real catalogue, from Part 2 of the form. (name, fee, pricing_unit,
# processing_time) - processing_time is left as-is where a row already has a
# published turnaround, since the form does not state one.
CATALOGUE = [
    ("Certification", Decimal("80.00"), "flat"),
    ("Diploma Replacement", Decimal("100.00"), "flat"),
    ("Form 137", Decimal("100.00"), "flat"),
    ("Evaluation", Decimal("50.00"), "flat"),
    ("Authentication", Decimal("5.00"), "per_page"),
    ("Honorable Dismissal", Decimal("100.00"), "flat"),
    ("CAV Certification", Decimal("125.00"), "flat"),
    ("Correction of Name", Decimal("100.00"), "flat"),
    ("Transcript of Records", Decimal("125.00"), "per_page"),
    ("Permit to Study", Decimal("100.00"), "flat"),
]

# Rows whose name was wrong, not just their price. Corrected in place rather
# than dropped and recreated, because transaction_type is PROTECT and these
# already have live requests pointing at them - a delete would either fail or
# orphan real history.
RENAMES = {
    "Certificate of Enrollment": "Certification",
    "Diploma - Second Copy": "Diploma Replacement",
}

# Not on the real form. Only removed if nothing references it; if a request
# does, it is left alone and reported rather than failing the migration.
RETIRED = ["Good Moral Certificate"]


def rename_purposes(apps, schema_editor):
    """Rewrite stored purposes to the form's own wording.

    form_data is JSON, so this cannot be a column-level UPDATE - each row is
    loaded, its one key rewritten, and saved back.
    """
    FormSubmission = apps.get_model("TrailSync", "FormSubmission")
    changed = 0
    for sub in FormSubmission.objects.all():
        data = sub.form_data or {}
        old = data.get("purpose")
        if old in PURPOSE_RENAMES:
            data["purpose"] = PURPOSE_RENAMES[old]
            sub.form_data = data
            sub.save(update_fields=["form_data"])
            changed += 1
    print(f"    renamed purpose on {changed} submission(s)")


def unrename_purposes(apps, schema_editor):
    FormSubmission = apps.get_model("TrailSync", "FormSubmission")
    back = {v: k for k, v in PURPOSE_RENAMES.items()}
    for sub in FormSubmission.objects.all():
        data = sub.form_data or {}
        if data.get("purpose") in back:
            data["purpose"] = back[data["purpose"]]
            sub.form_data = data
            sub.save(update_fields=["form_data"])


def correct_catalogue(apps, schema_editor):
    """Bring TRANSACTION_TYPES in line with FM-USTP-RGTR-09.

    Every fee in the previous catalogue was invented. This renames the two
    rows whose names were wrong, reprices the rest, adds the documents the
    form offers that were missing, and retires one that does not exist on the
    form at all.

    Existing FormRequest.amount_due values are deliberately NOT recomputed: a
    stamped amount is what a student was told to pay and may already have
    paid, and rewriting it to match a corrected fee schedule would falsify
    the record of that transaction.
    """
    TransactionType = apps.get_model("TrailSync", "TransactionType")
    FormRequest = apps.get_model("TrailSync", "FormRequest")

    for old_name, new_name in RENAMES.items():
        row = TransactionType.objects.filter(name=old_name).first()
        if row is None:
            continue
        if TransactionType.objects.filter(name=new_name).exclude(pk=row.pk).exists():
            # The correct name already exists; leave the stale row for a human
            # rather than silently merging two rows with live requests.
            print(f"    SKIPPED rename {old_name!r}: {new_name!r} already exists")
            continue
        row.name = new_name
        row.save(update_fields=["name"])
        print(f"    renamed {old_name!r} -> {new_name!r}")

    for name, fee, unit in CATALOGUE:
        row, created = TransactionType.objects.get_or_create(
            name=name, defaults={"fee_amount": fee, "pricing_unit": unit, "common_purposes": []}
        )
        if not created:
            row.fee_amount = fee
            row.pricing_unit = unit
            row.save(update_fields=["fee_amount", "pricing_unit"])
        print(f"    {'added  ' if created else 'priced '} {name}: {fee} ({unit})")

    for name in RETIRED:
        row = TransactionType.objects.filter(name=name).first()
        if row is None:
            continue
        in_use = FormRequest.objects.filter(transaction_type=row).count()
        if in_use:
            print(f"    KEPT {name!r}: {in_use} live request(s) reference it")
        else:
            row.delete()
            print(f"    retired {name!r} (not on the official form, unused)")


def uncorrect_catalogue(apps, schema_editor):
    """Reverse only the renames. Prices and added rows are left: restoring
    invented fees would be worse than leaving correct ones in place."""
    TransactionType = apps.get_model("TrailSync", "TransactionType")
    for old_name, new_name in RENAMES.items():
        row = TransactionType.objects.filter(name=new_name).first()
        if row is not None:
            row.name = old_name
            row.save(update_fields=["name"])


def fix_release_hours(apps, schema_editor):
    """Move seeded release slots into real releasing hours.

    The form prints "RELEASING TIME is from 3:00 to 5:00 in the afternoon";
    the seeded slots were at 9:00 and 13:00, so every one of them offered a
    window the office does not actually release in.

    Slots with a request already booked against them are left untouched - a
    student was told that time, and quietly moving it would make the claim
    stub in their hand wrong.
    """
    ReleaseSlot = apps.get_model("TrailSync", "ReleaseSlot")
    booked = set(
        ReleaseSlot.objects.filter(form_requests__isnull=False).values_list("id", flat=True)
    )
    stale = ReleaseSlot.objects.exclude(id__in=booked).exclude(
        start_time__gte="15:00", end_time__lte="17:00"
    )
    dates = sorted({s.slot_date for s in stale})
    removed = stale.count()
    stale.delete()

    for slot_date in dates:
        ReleaseSlot.objects.get_or_create(
            slot_date=slot_date,
            start_time="15:00",
            end_time="17:00",
            defaults={"available_slots": 20},
        )
    print(
        f"    removed {removed} slot(s) outside releasing hours, "
        f"reseeded {len(dates)} date(s) at 15:00-17:00"
        + (f", left {len(booked)} booked slot(s) alone" if booked else "")
    )


def restore_release_hours(apps, schema_editor):
    ReleaseSlot = apps.get_model("TrailSync", "ReleaseSlot")
    ReleaseSlot.objects.filter(start_time="15:00", end_time="17:00").delete()



class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0016_userprofile_birth_date_submissionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='pricing_unit',
            field=models.CharField(choices=[('flat', 'Flat fee'), ('per_page', 'Per page')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formrequest',
            name='request_status',
            field=models.CharField(choices=[('Submitted', 'Pending Verification'), ('Verified', 'Verified'), ('Approved', 'Approved - Ready to Print'), ('Processing', 'Processing'), ('Ready', 'Ready for Pickup'), ('Released', 'Released'), ('Rejected', 'Rejected')], default='Submitted', max_length=20),
        ),
            migrations.RunPython(rename_purposes, unrename_purposes),
        migrations.RunPython(correct_catalogue, uncorrect_catalogue),
        migrations.RunPython(fix_release_hours, restore_release_hours),
    ]
