# Generated by Django 6.0.7 on 2026-09-11 14:09

import TrailSync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0017_transactiontype_pricing_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=TrailSync.models.profile_picture_upload_to),
        ),
    ]
