# Generated by Django 6.0.7 on 2026-09-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0018_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tour_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
