# Generated by Django 6.0.7 on 2026-09-14 10:34

from django.db import migrations, models
from django.db.models import F


def backfill_verified(apps, schema_editor):
    """Everyone who already has an account counts as verified.

    They registered before verification existed and have been logging in
    since; making them re-prove an address they already use would lock out
    working accounts, staff included. Stamped with when they joined, which
    is the honest answer to "since when is this address trusted".
    """
    User = apps.get_model("TrailSync", "User")
    updated = User.objects.filter(email_verified=False).update(
        email_verified=True, email_verified_at=F("date_joined")
    )
    print(f"    marked {updated} existing account(s) as verified")


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0020_describe_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_category',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Alumni', 'Alumni')], max_length=50, null=True),
        ),
        # No reverse: un-verifying everyone would lock them out on rollback.
        migrations.RunPython(backfill_verified, migrations.RunPython.noop),
    ]
