# Generated by Django 6.0.7 on 2026-09-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0021_email_verification_and_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
