# Generated by Django 6.0.7 on 2026-09-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0022_transaction_type_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
