# Generated by Django 6.0.7 on 2026-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0024_academic_status_and_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='formrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formrequest',
            name='proxy_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formrequest',
            name='request_status',
            field=models.CharField(choices=[('Submitted', 'Pending Verification'), ('Verified', 'Verified'), ('Approved', 'Approved - Ready to Print'), ('Processing', 'Processing'), ('Ready', 'Ready for Pickup'), ('Released', 'Released'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Approved', 'Approved - Ready to Print'), ('Processing', 'Processing'), ('Ready', 'Ready for Pickup'), ('Released', 'Released'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
    ]
