# Generated by Django 6.0.7 on 2026-09-19 12:04

import TrailSync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0026_amount_due_locked_at_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='generated_pdf_path',
            field=models.FileField(blank=True, max_length=255, null=True, storage=TrailSync.models.private_storage, upload_to='official_forms/%Y/%m/'),
        ),
    ]
