# Generated by Django 6.0.7 on 2026-09-20 10:31

import TrailSync.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrailSync', '0028_transactiontype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Approved', 'Approved - Ready to Print'), ('Processing', 'Processing'), ('Ready', 'Ready for Pickup'), ('Released', 'Released'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Payment Proof', 'Payment proof')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image_path', models.ImageField(max_length=255, upload_to=TrailSync.models.receipt_upload_to)),
                ('student_entered_or_number', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Superseded', 'No longer needed')], default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('form_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='TrailSync.formrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proof_reviews', to='TrailSync.staffprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
