"""The student's claim stub: TrailSync's card template (assets/templates/Claim_Stub_fillable.pdf), filled by field name.

The card's design and where each field sits are made once by `manage.py build_pdf_templates`.
"""

from __future__ import annotations

from django.utils import timezone

from .pdf_forms import abbreviate, fill_pdf, local, money, student_name

TEMPLATE = "Claim_Stub_fillable.pdf"
EM_DASH = "—"
MIDDOT = "·"

REQUIRED_FIELDS = frozenset({
    "tracking_number", "name", "course", "date_of_request", "credential_requested", "date_of_release",
    "amount_assessed", "or_number", "issued_note",
})


def claim_stub_values(form_request) -> dict:
    user = form_request.user
    profile = getattr(user, "user_profile", None)
    course = profile.course if profile else None

    scheduled = form_request.scheduled_release()
    if scheduled is not None:
        release_date, release_time = scheduled
        when = f"{release_date:%B %d, %Y}"
        if release_time is not None:
            when += f" {MIDDOT} {release_time:%I:%M %p}"
    else:
        # Never a blank field: say it isn't scheduled yet.
        when = f"To be scheduled {EM_DASH} check back soon"

    issued = local(form_request.claim_stub_issued_at) or local(timezone.now())
    return {
        "tracking_number": form_request.request_code,
        "name": student_name(user, profile),
        # As on the official form: the course code when the full title won't fit at full size.
        "course": (course, abbreviate(course)) if course else EM_DASH,
        "date_of_request": f"{local(form_request.created_at):%B %d, %Y}",
        "credential_requested": form_request.transaction_type.name,
        "date_of_release": when,
        # Locked by the time the stub is downloadable (it goes live at payment), so printed as recorded.
        "amount_assessed": money(form_request.current_amount_due()) or EM_DASH,
        "or_number": form_request.or_number or EM_DASH,
        "issued_note": f"Issued {issued:%B %d, %Y at %I:%M %p} {MIDDOT} Generated by TrailSync.",
    }


def build_claim_stub_pdf(form_request) -> bytes:
    """The filled, flattened claim stub. Callers own authorisation and the digital_stub_active check."""
    return fill_pdf(
        TEMPLATE,
        claim_stub_values(form_request),
        set(),
        required=REQUIRED_FIELDS,
        metadata={
            "/Title": f"TrailSync Claim Stub — {form_request.request_code}",
            "/Author": "USTP-CDO Office of the Registrar",
            "/Subject": "Claim Stub",
        },
    )
